/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemen.karyawan;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ades
 */
public class FormCariPegRekap extends javax.swing.JFrame {
    String sql, sql1;
    Statement st, st1;
    Connection con;
    ResultSet rs, rs1;
    /**
     * Creates new form CariBarang
     */
    public FormCariPegRekap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdPeg = new javax.swing.JTextField();
        txtNamaPeg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelCari = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nama Pegawai");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ID Pegawai");

        txtIdPeg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPegActionPerformed(evt);
            }
        });
        txtIdPeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdPegKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdPegKeyReleased(evt);
            }
        });

        txtNamaPeg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNamaPeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaPegKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaPegKeyReleased(evt);
            }
        });

        tabelCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCariMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelCari);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamaPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPegActionPerformed
       
    }//GEN-LAST:event_txtIdPegActionPerformed

    private void txtIdPegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdPegKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              tabelCari.requestFocus();
        }
    }//GEN-LAST:event_txtIdPegKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tampilTabel();
    }//GEN-LAST:event_formWindowActivated

    private void txtNamaPegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPegKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              tabelCari.requestFocus();
        }
    }//GEN-LAST:event_txtNamaPegKeyPressed

    private void txtIdPegKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdPegKeyReleased
    tampilTabel();   
    }//GEN-LAST:event_txtIdPegKeyReleased

    private void txtNamaPegKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPegKeyReleased
    tampilTabel();        
    }//GEN-LAST:event_txtNamaPegKeyReleased

    private void tabelCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCariMouseClicked
        tampilData();
        dispose();
    }//GEN-LAST:event_tabelCariMouseClicked
    private  void tampilTabel(){
          DefaultTableModel tb = new DefaultTableModel();
          tb.addColumn("ID Pegawai");
          tb.addColumn("Nama Pegawai");
          tb.addColumn("No. Tlp");
          tb.addColumn("Email");
          tb.addColumn("Jabatan");
 
       try {
              con = Koneksi.getCon();
              if(txtIdPeg.getText().equals("")&& txtNamaPeg.getText().equals("")){
                  sql ="SELECT * FROM `pegawai` WHERE `JabatanPeg` ='pegawai'";
              }else if(txtNamaPeg.getText().equals("")){
                  sql = "select * from pegawai where id_pegawai LIKE "
                          + "\""+txtIdPeg.getText()+"%%\" && `JabatanPeg` ='pegawai'";
              }else if(txtIdPeg.getText().equals("")){
                  sql = "select * from pegawai where NamaPeg LIKE "
                          + "\""+txtNamaPeg.getText()+"%%\" && JabatanPeg ='pegawai'";
              }
              st = con.createStatement();
              rs = st.executeQuery(sql);
              tb.setRowCount(0);
              int i = 1;
              while (rs.next()){
                  Object[] data = new Object[5];
                  data[0] = rs.getString("id_pegawai");
                  data[1] = rs.getString("NamaPeg");
                  data[2] =  rs.getString("NoTlpPeg");
                  data[3] = rs.getString("EmailPeg");
                  data[4] = rs.getString("JabatanPeg");
                  tb.addRow(data);
                  i++;
                  
              
              }
              tabelCari.setModel(tb);
          } catch (Exception e) {
                  }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCariPegRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCariPegRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCariPegRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCariPegRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCariPegRekap().setVisible(true);
            }
        });
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelCari;
    private javax.swing.JTextField txtIdPeg;
    private javax.swing.JTextField txtNamaPeg;
    // End of variables declaration//GEN-END:variables

    private void tampilData() {
        try {
            int row = tabelCari.getSelectedRow();
            FormRekapPrisensiAdmin.txtNama.setText(tabelCari.getValueAt(row, 1).toString());
            FormRekapPrisensiAdmin.txtId.setText(tabelCari.getValueAt(row, 0).toString());
            FormRekapPrisensiAdmin.txtJabatan.setText(tabelCari.getValueAt(row, 4).toString());
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e,"Terjadi Kesalahan Menampilkan Data",JOptionPane.ERROR_MESSAGE);
       
        }
  
    }
}
