/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemen.karyawan;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static manajemen.karyawan.FormLogin.txtIdPeg;
import static manajemen.karyawan.FormLogin.txtNamaPeg;


/**
 *
 * @author krypton
 */
public class FormTodoList extends javax.swing.JFrame implements Master {
    
    private static final long serialVersionUID = 47612794125L;
       // warna background untuk baris ganjil
    private Color ganjil;
 
    // warna background untuk baris genap
    private Color genap;
    
    public String tgl;
    String sql,sql1;
    Statement st,st1;
    Connection con,con1;
    ResultSet rs,rs1;
    
    /**
     * Creates new form FormTodoList
     */
    public FormTodoList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtShowPeg = new javax.swing.JTextField();
        IdPeg = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        DayNow = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ToDoList");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("JobDesk :");

        txtShowPeg.setEditable(false);
        txtShowPeg.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtShowPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtShowPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        ListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Todo List", "Jam Mulai", "Jam AKhir"
            }
        ));
        jScrollPane2.setViewportView(ListTable);
        if (ListTable.getColumnModel().getColumnCount() > 0) {
            ListTable.getColumnModel().getColumn(0).setResizable(false);
            ListTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            ListTable.getColumnModel().getColumn(1).setMinWidth(440);
            ListTable.getColumnModel().getColumn(1).setPreferredWidth(440);
            ListTable.getColumnModel().getColumn(1).setMaxWidth(440);
            ListTable.getColumnModel().getColumn(2).setResizable(false);
            ListTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            ListTable.getColumnModel().getColumn(3).setResizable(false);
            ListTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jButton1.setText("Tambah / Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        DayNow.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Tgl :");

        Tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Job", "Job Desk", "Tanggal"
            }
        ));
        Tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb1);
        if (Tb1.getColumnModel().getColumnCount() > 0) {
            Tb1.getColumnModel().getColumn(0).setResizable(false);
            Tb1.getColumnModel().getColumn(0).setPreferredWidth(50);
            Tb1.getColumnModel().getColumn(1).setPreferredWidth(300);
            Tb1.getColumnModel().getColumn(2).setResizable(false);
            Tb1.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DayNow, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DayNow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ShowCurrentDate();
        
        IdPeg.setVisible(false);
        IdPeg.setText(txtIdPeg.getText());
        txtShowPeg.setText(txtNamaPeg.getText());
        
        FillListBox();
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        FormPegawai FP = new FormPegawai();
        FP.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb1MouseClicked
        // TODO add your handling code here:
          if (evt.getButton() == MouseEvent.BUTTON3) {
            // whatever
                StatusUpdate();
        }
          if(evt.getButton() == MouseEvent.BUTTON1){
                      tampilData();
          }

    }//GEN-LAST:event_Tb1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        FormTambahList FTL = new FormTambahList();
        FTL.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTodoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTodoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTodoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTodoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTodoList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DayNow;
    private javax.swing.JTextField IdPeg;
    private javax.swing.JTable ListTable;
    private javax.swing.JTable Tb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtShowPeg;
    // End of variables declaration//GEN-END:variables

    
    private void ShowCurrentDate() {
        con = Koneksi.getCon();
        
        try {
            sql = "SELECT current_date()";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            
            if (rs.next()){
                DayNow.setText(rs.getString("current_date()"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e,"Show Date Tidak Muncul !", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void FillListBox() {
        
        
        DefaultTableModel m = new DefaultTableModel();
        
        m.addColumn("Id");
        m.addColumn("Job Desk");
        m.addColumn("Tanggal");
        m.addColumn("Status");

        con = Koneksi.getCon();
        try {
            String tugas ;
            String sql="SELECT * FROM `job_desk` INNER JOIN pegawai ON job_desk.id_pegawai = pegawai.id_pegawai WHERE job_desk.id_pegawai ='"+ txtIdPeg.getText() +"'";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            m.setRowCount(0);
     
            int i = 1;
            while (rs.next()) {
                Object[] data = new Object[4];
                data[0] = rs.getString("id_job");
                data[1] = rs.getString("NamaJob");
                data[2] = rs.getString("tanggal");
                String a = rs.getString("StatusJob");
                int b = Integer.parseInt(a);
                if(b == 1){
                       tugas = "Selesai";
                }else{
                     tugas = "Belom Selesai";
                
                }
                     data[3] = tugas;
                
                m.addRow(data);
                i++;
            }
            Tb1.setModel(m);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Kesalahan Tampil Job Desk !", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    @Override
    public void tambahData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ubahData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void hapusData() {
        con = Koneksi.getCon();
        try {
            
            int row = ListTable.getSelectedRow();
            String IdTodo = ListTable.getModel().getValueAt(row, 0).toString();
            
            int pilihan = JOptionPane.showConfirmDialog(null, "Yakin Menghapus list ini ?", "Peringatan !!!", JOptionPane.YES_NO_OPTION);
            if (pilihan==JOptionPane.YES_OPTION) {
                sql="DELETE FROM to_do_list_job WHERE id_to_do_list='"+ IdTodo +"'";
            }
           
            st=con.createStatement();
            st.execute(sql);
            
            tampilData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Kesalahan Hapus !", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void tampilData() {
        DefaultTableModel DTM = new DefaultTableModel();
        
        DTM.addColumn("Id");
        DTM.addColumn("Todo List");
        DTM.addColumn("Jam Mulai");
        DTM.addColumn("Jam Akhir");
        
        con = Koneksi.getCon();
        try {
            int row = Tb1.getSelectedRow();
            String IdJob = Tb1.getModel().getValueAt(row, 0).toString();
            System.out.println(IdJob);
            String sql="SELECT to_do_list_job.id_to_do_list, to_do_list_job.todolist, to_do_list_job.jam_batas_mulai, to_do_list_job.jam_batas_akhir FROM to_do_list_job WHERE to_do_list_job.id_job='"+ IdJob +"'";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            DTM.setRowCount(0);
            int i = 1;
            while (rs.next()) {
                
                Object[] data = new Object[4];
                data[0] = rs.getString("id_to_do_list");
                data[1] = rs.getString("todolist");
                data[2] = rs.getString("jam_batas_mulai");
                data[3] = rs.getString("jam_batas_akhir");
                DTM.addRow(data);
                i++;
            }
            ListTable.setModel(DTM);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Kesalahan Tampil Todo List !", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void bersihForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void StatusUpdate() {
             con = Koneksi.getCon();
        try {
            
                 int row = Tb1.getSelectedRow();
            String IdJob = Tb1.getModel().getValueAt(row, 0).toString();
            
            int pilihan = JOptionPane.showConfirmDialog(null, "Anda Yakin Sudah Selesai ?", "Peringatan !!!", JOptionPane.YES_NO_OPTION);
            if (pilihan==JOptionPane.YES_OPTION) {
                sql="UPDATE `job_desk` SET `StatusJob` = '1' WHERE `job_desk`.`id_job` = '"+IdJob+"'";
            }else{
                 sql="UPDATE `job_desk` SET `StatusJob` = '0' WHERE `job_desk`.`id_job` = '"+IdJob+"'";
            }
           
            st=con.createStatement();
            st.execute(sql);
            
         FillListBox();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Status Upadate Hapus !", JOptionPane.ERROR_MESSAGE);
        }
    }
}
