/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package manajemen.karyawan;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import static manajemen.karyawan.FormLogin.txtIdPeg;

/**
 *
 * @author krypton
 */
public class FormTambahList extends javax.swing.JFrame implements Master {
    public String tgl;
    String sql;
    Statement st;
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    

    /** Creates new form FormTambahList */
    public FormTambahList() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idJob = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SelectJob = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTDL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        txtJamMulai = new javax.swing.JSpinner(sm);
        Date date1 = new Date();
        SpinnerDateModel sm1 =
        new SpinnerDateModel(date1, null, null, Calendar.HOUR_OF_DAY);
        txtJamAkhir = new javax.swing.JSpinner(sm1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        idJob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idJobKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Id :");

        SelectJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Job Desk :");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("to do list : ");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("jam batas mulai : ");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("jam batas akhir : ");

        jButton1.setText("tambah");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("simpan");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("format waktu : hh:mm:ss");

        JSpinner.DateEditor de = new JSpinner.DateEditor(txtJamMulai, "HH:mm:ss");
        txtJamMulai.setEditor(de);

        JSpinner.DateEditor de1 = new JSpinner.DateEditor(txtJamAkhir, "HH:mm:ss");
        txtJamAkhir.setEditor(de1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idJob, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(txtJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtJamAkhir))
                            .addGap(59, 59, 59)
                            .addComponent(jLabel6))
                        .addComponent(txtTDL)
                        .addComponent(SelectJob, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtJamAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        tambahData();
    }//GEN-LAST:event_jButton1MouseClicked

    private void idJobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idJobKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            tampilData();
            SelectJob.requestFocus();
    }//GEN-LAST:event_idJobKeyPressed
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        tampil_combo();
    }//GEN-LAST:event_formWindowActivated

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        con = Koneksi.getCon();
        try {
            sql = "SELECT * FROM to_do_list_job WHERE id_to_do_list='"+ idJob.getText() +"'";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                ubahData();
                dispose();
                FormTodoList FTL = new FormTodoList();
                FTL.setVisible(true);
            } else {
                tambahData();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error ubah data!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTambahList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTambahList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTambahList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTambahList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTambahList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelectJob;
    private javax.swing.JTextField idJob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner txtJamAkhir;
    private javax.swing.JSpinner txtJamMulai;
    private javax.swing.JTextField txtTDL;
    // End of variables declaration//GEN-END:variables

    
    public void tampil_combo() {
        con = Koneksi.getCon();
        
        try {
            sql = "SELECT * FROM job_desk WHERE id_pegawai='"+ txtIdPeg.getText() +"'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            
            while(rs.next()) {
                SelectJob.addItem(rs.getString("id_job"));
            }
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e,"Combo Box Error !", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void tambahData() {
        con = Koneksi.getCon();
          String pattern = "HH:mm:ss";
                SimpleDateFormat aa = new SimpleDateFormat(pattern);
        try {
            String waktu1 = String.valueOf(aa.format(txtJamMulai.getValue()));
            String waktu2 = String.valueOf(aa.format(txtJamAkhir.getValue()));
            String JobDDesk = SelectJob.getSelectedItem().toString();
            
            sql="INSERT INTO to_do_list_job VALUES('"+ idJob.getText() +"', '"+ JobDDesk +"', '"+ txtTDL.getText() +"', '"+ waktu1 +"', '"+ waktu2 +"', CURRENT_DATE)";
            st = con.createStatement();
            st.execute(sql);
            
            dispose();
            FormTodoList FTL = new FormTodoList();
            FTL.setVisible(true);
            
            
            FormTodoList list = new FormTodoList();
            list.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e,"Tambah Data Error !", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void ubahData() {
        con = Koneksi.getCon();
              String pattern = "HH:mm:ss";
                SimpleDateFormat aa = new SimpleDateFormat(pattern);
        try {
              String waktu1 = String.valueOf(aa.format(txtJamMulai.getValue()));
            String waktu2 = String.valueOf(aa.format(txtJamAkhir.getValue()));
            String JobDDesk = SelectJob.getSelectedItem().toString();
            
            sql = "UPDATE to_do_list_job SET id_job='"+ JobDDesk +"', todolist='"+ txtTDL.getText() +"', jam_batas_mulai='"+ waktu1 +"', jam_batas_akhir='"+ waktu2 +"', tanggal=CURRENT_DATE WHERE id_to_do_list='"+ idJob.getText() +"'";
            st = con.createStatement();
            st.execute(sql);
            JOptionPane.showMessageDialog(null, "Update data berhasil !");
        } catch (Exception e) {
            
        }
    }

    @Override
    public void hapusData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void tampilData() {
        con = Koneksi.getCon();

        try {
       
            sql = "SELECT * FROM to_do_list_job WHERE id_to_do_list='"+ idJob.getText() +"'";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()) {
          
                       
                SelectJob.setSelectedItem(rs.getString("id_job"));
                txtTDL.setText(rs.getString("todolist"));
                txtJamMulai.setValue(rs.getTime("jam_batas_mulai"));
                txtJamAkhir.setValue(rs.getTime("jam_batas_akhir"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e,"Tampil Data Error !", JOptionPane.ERROR_MESSAGE);
        }
    }
    @Override
    public void bersihForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
