/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemen.karyawan;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ades
 */
public class FormTambahPeg extends javax.swing.JFrame implements Master {
    String sql,sql1;
    Statement st,st1;
    Connection con,con1;
    ResultSet rs,rs1;
    
    /**
     * Creates new form FormTambahPeg
     */
    public FormTambahPeg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJenisKelamin = new javax.swing.ButtonGroup();
        status = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtNamaPeg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNoTlp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtJabatan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        L = new javax.swing.JRadioButton();
        P = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtGaji = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPeg = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRubah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdPeg = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        btnBerisih = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        txtPw = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        rdaktif = new javax.swing.JRadioButton();
        rdnon = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Id Pegawai");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Email");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");

        txtNamaPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPegActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("No. Telp.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jabatan");

        txtJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pegawai", "Supervisor", "Admin" }));
        txtJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJabatanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Kelamin");

        txtJenisKelamin.add(L);
        L.setText("Laki-Laki");

        txtJenisKelamin.add(P);
        P.setText("Perempuan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Gaji");

        tblPeg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPegMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPeg);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRubah.setText("Rubah");
        btnRubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRubahActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Username");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Password");

        txtIdPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPegActionPerformed(evt);
            }
        });
        txtIdPeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdPegKeyPressed(evt);
            }
        });

        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        btnBerisih.setText("Bersih");
        btnBerisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerisihActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Form Tambah Pegawai");

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Status");

        status.add(rdaktif);
        rdaktif.setText("Aktif");

        status.add(rdnon);
        rdnon.setText("NonAktif");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEmail)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNamaPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(L)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(P))
                                            .addComponent(txtIdPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCek)
                                        .addComponent(txtUsername)
                                        .addComponent(txtPw, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdaktif)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdnon))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnRubah)
                                .addGap(18, 18, 18)
                                .addComponent(btnBerisih)
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar)
                                .addGap(144, 144, 144))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(229, 229, 229))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(L)
                    .addComponent(P)
                    .addComponent(jLabel10)
                    .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(rdaktif)
                        .addComponent(rdnon)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnRubah)
                    .addComponent(btnBerisih)
                    .addComponent(btnKeluar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        L.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJabatanActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       tampilTabel();
    }//GEN-LAST:event_formWindowActivated

    private void txtNamaPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPegActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
         con = Koneksi.getCon();
        try {
            sql = "select * from ak_login where username='"+txtUsername.getText()+"'";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            boolean adaData = rs.next();
            if(adaData == true){
               JOptionPane.showMessageDialog(this, "Username Tidak Dapat Digunakan");
            }else{
            
              JOptionPane.showMessageDialog(this, "Username Dapat Digunakan");
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e, "Pesen Kesalahan Cek Username", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       tambahData();
       tampilTabel();
       bersihForm();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtIdPegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdPegKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
               tampilData();
        txtNamaPeg.requestFocus();
    
        }
    }//GEN-LAST:event_txtIdPegKeyPressed

    private void btnBerisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerisihActionPerformed
      bersihForm();
    }//GEN-LAST:event_btnBerisihActionPerformed

    private void btnRubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRubahActionPerformed
       ubahData();
       tampilTabel();
    }//GEN-LAST:event_btnRubahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        hapusData();
        tampilTabel();
        bersihForm();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tblPegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPegMouseClicked
       hapustb();
    }//GEN-LAST:event_tblPegMouseClicked

    private void txtIdPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPegActionPerformed

      private  void tampilTabel(){
          DefaultTableModel tb = new DefaultTableModel();
          tb.addColumn("Id Pegawai");
          tb.addColumn("Nama Pegawai");
          tb.addColumn("Alamat");
          tb.addColumn("J. Kelamin");
          tb.addColumn("Jabatan");
          tb.addColumn("Username");
 
          try {
              con = Koneksi.getCon();
              sql = "SELECT * FROM pegawai INNER JOIN ak_login on pegawai.id_pegawai = ak_login.id_pegawai";
              st = con.createStatement();
              rs = st.executeQuery(sql);
              tb.setRowCount(0);
              int i = 1;
              while (rs.next()){
                  Object[] data = new Object[6];
                  data[0] = rs.getString("id_pegawai");
                  data[1] = rs.getString("NamaPeg");
                  data[2] = rs.getString("AlamatPeg");
                  data[3] =  (rs.getString("jenis_kelamin").equals("L"))? "Laki-Laki" : "Perempuan";
                  data[4] = rs.getString("JabatanPeg");
                  data[5] = rs.getString("username");
                  tb.addRow(data);
                  i++;
                  
              
              }
              tblPeg.setModel(tb);
          } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e,"Terjadi Kesalahan Tampil Tabel",JOptionPane.ERROR_MESSAGE);
          }
      
      }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTambahPeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTambahPeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTambahPeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTambahPeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTambahPeg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton L;
    private javax.swing.JRadioButton P;
    private javax.swing.JButton btnBerisih;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnRubah;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdaktif;
    private javax.swing.JRadioButton rdnon;
    private javax.swing.ButtonGroup status;
    private javax.swing.JTable tblPeg;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtIdPeg;
    private javax.swing.JComboBox<String> txtJabatan;
    private javax.swing.ButtonGroup txtJenisKelamin;
    private javax.swing.JTextField txtNamaPeg;
    private javax.swing.JTextField txtNoTlp;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tambahData() {
      String Jkel = (L.isSelected() ? "L" : "P");
      String status = (rdaktif.isSelected() ? "aktif" : "nonaktif");
         String jb = txtJabatan.getSelectedItem().toString();
        con = Koneksi.getCon();
        try {
            sql ="INSERT INTO pegawai values('"+txtIdPeg.getText()+"'"
                    + ",'"+txtNamaPeg.getText()+"'"
                    + ",'"+Jkel+"'"
                    + ",'"+txtAlamat.getText()+"'"
                    + ",'"+txtEmail.getText()+"'"
                    + ",'"+txtNoTlp.getText()+"'"
                    + ",'"+jb+"'"
                    + ",'"+txtGaji.getText()+"')";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Pesen Kesalahan Tambah Data pegawai", JOptionPane.ERROR_MESSAGE);
        }
             try {
            sql ="INSERT INTO ak_login values("
                    + "'"+txtIdPeg.getText()+"'"
                    + ",'"+txtUsername.getText()+"'"
                    + ",'"+txtPw.getText()+"'"
                    + ",'"+status+"')";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Pesen Kesalahan Tambah Data ak_login", JOptionPane.ERROR_MESSAGE);
        }  
    }

    @Override
    public void ubahData() {
        Connection con = Koneksi.getCon(); 
         String Jkel = (L.isSelected() ? "L" : "P");
               String status = (rdaktif.isSelected() ? "aktif" : "nonaktif");
         String jb = txtJabatan.getSelectedItem().toString();
        try {
            sql ="UPDATE `pegawai` SET "
                    + "`NamaPeg` = '"+txtNamaPeg.getText()+"'"
                    + ",`Jenis_kelamin` = '"+Jkel+"'"
                    + ",`AlamatPeg` = '"+txtAlamat.getText()+"'"
                    + ",`EmailPeg` = '"+txtEmail.getText()+"'"
                    + ",`NoTlpPeg` = '"+txtNoTlp.getText()+"'"
                    + ",`JabatanPeg` = '"+jb+"'"
                    + ",`gaji` = '"+txtGaji.getText()+"'"
                    + "WHERE `pegawai`.`id_pegawai` = '"+txtIdPeg.getText()+"'";
            st=con.createStatement();
            st.execute(sql);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e,"Pesan Kesalahan Update pegawai", JOptionPane.ERROR_MESSAGE);
        }
             try {
            sql ="UPDATE `ak_login` SET "
                    + "`username` = '"+txtUsername.getText()+"'"
                    + ",`password` = '"+txtPw.getText()+"'"
                    + ",`status` = '"+status+"'"
                    + "WHERE `ak_login`.`id_pegawai` = '"+txtIdPeg.getText()+"'";
            st=con.createStatement();
            st.execute(sql);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e,"Pesan Kesalahan Update ak_login", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void hapusData() {
        Connection con = Koneksi.getCon();
        try {
            sql ="DELETE FROM `pegawai` WHERE `pegawai`.`id_pegawai` = '"+txtIdPeg.getText()+"'";
            st=con.createStatement();
            st.execute(sql);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e,"Pesan Kesalahan hapus pegawai", JOptionPane.ERROR_MESSAGE);
        }    
        try {
            sql ="DELETE FROM `ak_login` WHERE `ak_login`.`id_pegawai` = '"+txtIdPeg.getText()+"'";
            st=con.createStatement();
            st.execute(sql);
           
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e,"Pesan Kesalahan hapus ak_login", JOptionPane.ERROR_MESSAGE);
        }  
    }

    @Override
    public void tampilData() {
             Connection con = Koneksi.getCon();
         
        try {
              sql = "select * from ak_login INNER JOIN pegawai on ak_login.id_pegawai = pegawai.id_pegawai"
                    + " where pegawai.id_pegawai='"+txtIdPeg.getText()+"'";
            st=con.createStatement();
            rs= st.executeQuery(sql);
            
          
            while(rs.next()){
                txtNamaPeg.setText(rs.getString("NamaPeg"));
                txtAlamat.setText(rs.getString("AlamatPeg"));
                boolean jk = rs.getString("Jenis_kelamin").equals("L");
                if(jk == true){
                    L.setSelected(true);
                }else{
                    P.setSelected(true);
                }
                txtEmail.setText(rs.getString("EmailPeg"));
                txtNoTlp.setText(rs.getString("NoTlpPeg"));
                txtJabatan.setSelectedItem(rs.getString("JabatanPeg"));
                txtGaji.setText(rs.getString("gaji"));
                txtUsername.setText(rs.getString("username"));
                txtPw.setText(rs.getString("password"));
                   boolean st = rs.getString("status").equals("aktif");
                if(st == true){
                    rdaktif.setSelected(true);
                }else{
                    rdnon.setSelected(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e,"Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void bersihForm() {
          txtIdPeg.setText("");
          txtNamaPeg.setText("");
          L.setSelected(true);
          txtEmail.setText("");
          txtAlamat.setText("");
          txtNoTlp.setText("");
          txtGaji.setText("");
          txtUsername.setText("");
          txtPw.setText("");
    }
        public void hapustb(){
    
         con = Koneksi.getCon();
        try {
            int row = tblPeg.getSelectedRow();
            String id_peg = tblPeg.getValueAt(row, 0).toString();
            int pilih = JOptionPane.showConfirmDialog(null, "Yakin Mau Hapus Item Ini?"
                    , "Peringatan", JOptionPane.YES_OPTION);
            if(pilih==JOptionPane.YES_OPTION){
                sql = "DELETE FROM `pegawai` WHERE `pegawai`.`id_pegawai` = \'"+id_peg+"\'";
                sql1 = "DELETE FROM `ak_login` WHERE `ak_login`.`id_pegawai` = \'"+id_peg+"\'";
                System.out.print(sql);
            }
            st = con.createStatement();
            st.execute(sql);
            
            st = con.createStatement();
            st.execute(sql1);
            
            tampilTabel();
        } catch (Exception e) {
        }
    
    }
    

}
