/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemen.karyawan;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 * 
 *
 * @author toshiba
 */
public class JobDesk extends javax.swing.JFrame implements Master{
    public String tgl;
    String sql,sql1;
    Statement st,st1;
    Connection con,con1;
    ResultSet rs,rs1;
    FormCariPegawai caripegawai = new FormCariPegawai();
    FormCariSv sv = new FormCariSv();
    /**
     * Creates new form JobDesk
     */
    public JobDesk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtidjob = new javax.swing.JTextField();
        txtidpegawai = new javax.swing.JTextField();
        txtnamajob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnamapegawai = new javax.swing.JTextField();
        txtsupervisor = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeljobdesk = new javax.swing.JTable();
        jtanggal = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("JOB DESK PEGAWAI");

        jLabel2.setText("id_job");

        jLabel3.setText("id_pegawai");

        jLabel4.setText("NamaJob");

        jLabel5.setText("tanggal");

        jLabel7.setText("supervisor");

        txtidjob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidjobKeyPressed(evt);
            }
        });

        txtidpegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidpegawaiKeyPressed(evt);
            }
        });

        jLabel8.setText("NamaPegawai");

        txtsupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupervisorActionPerformed(evt);
            }
        });
        txtsupervisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsupervisorKeyPressed(evt);
            }
        });

        btnsubmit.setText("Simpan");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        tabeljobdesk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeljobdesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeljobdeskMouseClicked(evt);
            }
        });
        tabeljobdesk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabeljobdeskKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabeljobdesk);

        jtanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtanggalPropertyChange(evt);
            }
        });

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnamajob, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtsupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnsubmit)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtnamapegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidpegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidjob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidjob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamapegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsubmit))
                    .addComponent(jtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnamajob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
           con = Koneksi.getCon();
        try {
            sql = "select * from job_desk where id_job ='"+txtidjob.getText()+"'";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            boolean adaData = rs.next();
            if(adaData == true){
                ubahData();
            }else{
                tambahData();
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e, "Pesen Kesalahan Simpan", JOptionPane.ERROR_MESSAGE);
        }
        bersihForm();
        tampilTabel();
        
     
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtsupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupervisorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        tampilTabel();
    }//GEN-LAST:event_formWindowActivated

    private void jtanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtanggalPropertyChange
        try {
            if(jtanggal.getDate() != null){
                String pattern = "yyyy-MM-dd";
                SimpleDateFormat tanggal = new SimpleDateFormat(pattern);
                tgl = String.valueOf(tanggal.format(jtanggal.getDate()));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jtanggalPropertyChange

    private void txtidpegawaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpegawaiKeyPressed
     if(evt.getKeyCode()==KeyEvent.VK_F1){
          FormCariPegawai cr = new FormCariPegawai();
           cr.setVisible(true);
        }
    }//GEN-LAST:event_txtidpegawaiKeyPressed

    private void txtsupervisorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupervisorKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_F1){
          FormCariSv cr = new FormCariSv();
           cr.setVisible(true);
        }
    }//GEN-LAST:event_txtsupervisorKeyPressed

    private void txtidjobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidjobKeyPressed
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){
               tampilData();
        txtidpegawai.requestFocus();
        }
    }//GEN-LAST:event_txtidjobKeyPressed

    private void tabeljobdeskKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabeljobdeskKeyPressed
    }//GEN-LAST:event_tabeljobdeskKeyPressed

    private void tabeljobdeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeljobdeskMouseClicked
              hapustb();
    }//GEN-LAST:event_tabeljobdeskMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobDesk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jtanggal;
    private javax.swing.JTable tabeljobdesk;
    private javax.swing.JTextField txtidjob;
    public static javax.swing.JTextField txtidpegawai;
    public static javax.swing.JTextField txtnamajob;
    public static javax.swing.JTextField txtnamapegawai;
    public static javax.swing.JTextField txtsupervisor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tambahData() {
   String pattern = "HH:mm:ss";
                SimpleDateFormat aa = new SimpleDateFormat(pattern);

          
        con = Koneksi.getCon();
        try {
            sql="INSERT INTO job_desk values('"+txtidjob.getText()+"'"
                    +",'"+txtidpegawai.getText()+"'"
                    +",'"+txtnamajob.getText()+"'"
                    +",'"+tgl+"'"
                    +",'"+txtsupervisor.getText()+"'"
                    +",'"+0+"')";
             st = con.createStatement();
             st.execute(sql);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e, "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void tampilTabel(){
        String tugas ;
            DefaultTableModel tb = new DefaultTableModel();
            tb.addColumn("Id Job");
            tb.addColumn("Id Pegawai");
            tb.addColumn("Nama Pegawai");
            tb.addColumn("Nama Job");
            tb.addColumn("Tanggal");
            tb.addColumn("Supervisor");
            tb.addColumn("Status");
 
            try {
            con = Koneksi.getCon();
            sql = "SELECT * FROM `job_desk` INNER JOIN pegawai on job_desk.id_pegawai "
                    + "= pegawai.id_pegawai";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            tb.setRowCount(0);
            int i = 1;
            while (rs.next()){
                Object[] data = new Object[7];
                data [0] = rs.getString("id_job");
                data [1] = rs.getString("id_pegawai");
                data [2] = rs.getString("NamaPeg");
                data [3] = rs.getString("NamaJob");
                data [4] = rs.getDate("tanggal");
                data [5] = rs.getString("supervisor");
                       String a = rs.getString("StatusJob");
                int b = Integer.parseInt(a);
                if(b == 1){
                       tugas = "Selesai";
                }else{
                     tugas = "Belom Selesai";
                
                }
                data [6] = tugas;
                tb.addRow(data);
                i++;
            }
            tabeljobdesk.setModel(tb);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "TERJADI ERROR INPUT DATA", JOptionPane.ERROR_MESSAGE);
        }
    }
    @Override
    public void ubahData() {
          String pattern = "HH:mm:ss";
          SimpleDateFormat aa = new SimpleDateFormat(pattern);

          
           Connection con = Koneksi.getCon(); 
        try {
            sql ="UPDATE `job_desk` SET "
                    + "`id_pegawai` = '"+txtidpegawai.getText()+"'"
                    + ",`NamaJob` = '"+txtnamajob.getText()+"'"
                    + ",`tanggal` = '"+tgl+"'"
                    + ",`supervisor` = '"+txtsupervisor.getText()+"'"
                    + "WHERE `job_desk`.`id_job` = '"+txtidjob.getText()+"'";
            st=con.createStatement();
            st.execute(sql);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e,"Pesan Kesalahan Update", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void hapusData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void tampilData() {
            Connection con = Koneksi.getCon();
         
        try {
              sql = "SELECT * FROM `job_desk` INNER JOIN pegawai on job_desk.id_pegawai = pegawai.id_pegawai"
                      + " where job_desk.id_job = '"+txtidjob.getText()+"'";
            st=con.createStatement();
            rs= st.executeQuery(sql);
            
          
            while(rs.next()){
                txtidpegawai.setText(rs.getString("id_pegawai"));
                txtnamajob.setText(rs.getString("NamaJob"));
                txtnamapegawai.setText(rs.getString("NamaPeg"));
                jtanggal.setDate(rs.getDate("tanggal"));
                txtsupervisor.setText(rs.getString("supervisor"));
    
         
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e,"Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void bersihForm() {
              txtidjob.setText("");
              txtidpegawai.setText("");
              txtnamajob.setText("");
              txtnamapegawai.setText("");
              txtsupervisor.setText("");
    }
       public void hapustb(){
    
         con = Koneksi.getCon();
        try {
            int row = tabeljobdesk.getSelectedRow();
            String id_job = tabeljobdesk.getValueAt(row, 0).toString();
            int pilih = JOptionPane.showConfirmDialog(null, "Yakin Mau Hapus Item Ini?"
                    , "Peringatan", JOptionPane.YES_OPTION);
            if(pilih==JOptionPane.YES_OPTION){
                sql = "DELETE FROM `job_desk` WHERE `id_job` = \'"+id_job+"\'";
                System.out.print(sql);
            }
            st = con.createStatement();
            st.execute(sql);
            
            tampilTabel();
        } catch (Exception e) {
        }
    
    }
}
